-- French localization file for frFR.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local frFR = AceLocale:NewLocale("YssBossLoot", "frFR")
if not frFR then return end

frFR["2D Skulls"] = "Crânes en 2D"
frFR["3D_Skull_Detect_MSG"] = "|cffffd200YssBossLoot a détecté %s !|r|n|nSouhaitez-vous l'utiliser comme crâne représentant les boss ?"
frFR["Add Tooltip Info"] = "Ajout info Tooltip"
frFR["Animated Background"] = "Arrière-plan animé"
frFR["Boss Font Size"] = "Taille de police des boss"
frFR["Boss Frame Size"] = "Taille du cadre des boss"
frFR["Check All"] = "Tout cocher"
frFR["Class Filter"] = "Filtrer par classe"
frFR["Don't Want:"] = "Je ne veux pas :"
frFR["Dungeon"] = "Donjon"
frFR["Equip Location Filter"] = "Filtrage par emplacement"
frFR["Filter"] = "Filtrer"
frFR["Filter All"] = "Tout filtrer"
frFR["Filter All desc"] = "Grâce à des filtres qui se chevauchent|n vous devrez sans doute désactiver deux filtres|n ou plus après l'utilisation des touches de filtre."
frFR["Heroic 10-man Loot"] = "Butin en héroïque (10)"
frFR["Heroic 25-man Loot"] = "Butin en héroïque (25)"
frFR["Heroic Loot"] = "Butin en mode héroïque"
frFR["Hide Loot"] = "Cacher le butin"
frFR["Hides this sub type from being displayed"] = "Empêche ce sous-type d'être affiché."
frFR["Instance Type"] = "Type d'instance"
frFR["Item Stat Filter"] = "Filtre des statistiques des objets"
frFR["Item Type Filter"] = "Filtrage par type"
frFR["Large Map"] = "Grande carte"
frFR["Large Map with Objectives"] = "Grande carte avec objectifs"
frFR["Loot"] = "Butin"
frFR["Loot Scaling"] = "Échelle du butin"
frFR["Minimap Icon"] = "Icône de la minicarte"
frFR["No Class Restriction"] = "Pas de restriction de classe"
frFR["Normal 10-man Loot"] = "Butin en normal (10)"
frFR["Normal 25-man Loot"] = "Butin en normal (25)"
frFR["Normal Loot"] = "Butin en mode normal"
frFR["Only Type/SubType combinations you have previously seen can be filtered by default"] = "Uniquement les combinaisons de type /sous-type que vous avez vu précédemment peuvent être filtrés par défaut"
frFR["Only equip location you have previously seen can be filtered by default"] = "Seuls doter d'emplacement que vous avez vu précédemment peuvent être filtrés par défaut"
frFR["Only item stats you have previously seen can be filtered by default"] = "Seules les statistiques des objets que vous avez vu précédemment peuvent être filtrés par défaut"
frFR["Open to Current Instance Difficulty"] = "Ouvrir à la difficulté de l'instance actuelle"
frFR["Open to Currently Selected Difficulty in Group"] = "Ouvrir à la difficulté de l'instance actuelle en groupe"
frFR["Open to Currently Selected Difficulty in Group desc"] = "Ouvre à la difficulté actuelle si vous êtes en groupe mais toujours à l'extérieur de l'instance."
frFR["Raid"] = "Raid"
frFR["Show All"] = "Tout afficher"
frFR["Show this sub type"] = "Afficher ce sous-type"
frFR["Small Map"] = "Petite carte"
frFR["UNSAVE_QUERY_MSG"] = [=[|cFF33FF99YssBossLoot|r a détecté que vous avez été récemment déconnecté. Ceci est peut-être causé par l'analyse de trop de |cffff2020liens d'objet peu sûrs|r trop rapidement, ce qui augmente vos chances de déconnexion répétées pendant l'analyse.

|cffffd200Souhaitez-vous continuer l'analyse ?|r]=]
frFR["Uncheck All"] = "Tout décocher"
frFR["Use 3D Skull"] = "Utiliser le crâne en 3D"
frFR["Want:"] = "Je veux :"
frFR["When selected items with this class restriction will be shown"] = "Quand coché, les objets avec cette restriction de classe seront affichés."
frFR["When selected this item equip location will be filtered out"] = "Quand coché, cet emplacement d'objet sera éliminé par filtrage."
frFR["When selected this item equip location will be shown"] = "Quand coché, cet emplacement d'objet sera affiché."
frFR["When selected this item stat will be filtered out"] = "Quand coché, cette statistique d'objet sera éliminé par filtrage."
frFR["When selected this item type will be hidden unless multible subtypes are found"] = "Quand coché, ce type d'objet sera caché à moins que de multiples sous-types sont trouvés."
frFR["When selected this item type will be shown unless multible subtypes are found"] = "Quand coché, ce type d'objet sera affiché à moins que plusieurs sous-types ne soient trouvés."
frFR["Yellow Checkmark:|nWe want this stat.|n|nGrey Checkmark:|nWe do not care if we have this stat or not.|n|nNo Checkmark:|nWe do not want this stat."] = "Coche jaune :|nNous voulons cette stat.|n|nCoche grise :|nPeut importe si cette stat est présente ou non.|n|nPas de coche :|n Nous ne voulons pas de cette stat."
-- frFR["|cFFFF0000<<WARNING>>|r|nIf you change these from the default grey checkmark you may missout on items with no stats.|nOnly item stats you have previously seen can be filtered by default"] = "|cFFFF0000<<WARNING>>|r|nIf you change these from the default grey checkmark you may missout on items with no stats.|nOnly item stats you have previously seen can be filtered by default"
frFR["|cffffff00Click|r to open YssBossLoot Options"] = "|cffffff00Clic gauche|r pour ouvrir les options de YssBossLoot."
frFR["|cffffff00Click|r to toggle YssBossLoot"] = "|cffffff00Clic gauche|r pour afficher/cacher YssBossLoot."
frFR["|cffffff00Left Click|r to select Instance"] = "|cffffff00Clic gauche|r pour sélectionner une instance."
frFR["|cffffff00Right Click|r to open Options"] = "|cffffff00Clic droit|r pour ouvrir les options."

